In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing
import pickle

In [2]:
df = pd.read_csv("censu_regressao_tratado.csv")

In [3]:
len(df)

74001

In [4]:
df.isnull().sum()

TractId               0
State                 0
County                0
TotalPop              0
Men                   0
Women                 0
Hispanic              0
White                 0
Black                 0
Native                0
Asian                 0
Pacific               0
VotingAgeCitizen      0
Income                0
IncomeErr             0
IncomePerCap          0
IncomePerCapErr       0
Poverty               0
ChildPoverty          0
Professional          0
Service               0
Office                0
Construction          0
Production            0
Drive                 0
Carpool               0
Transit               0
Walk                  0
OtherTransp           0
WorkAtHome            0
MeanCommute           0
Employed              0
PrivateWork           0
PublicWork            0
SelfEmployed          0
FamilyWork            0
Unemployment        810
dtype: int64

In [5]:
df.head(5)

TractId    State          County  TotalPop   Men  Women  Hispanic  \
0  1001020100  Alabama  Autauga County      1845   899    946       2.4   
1  1001020200  Alabama  Autauga County      2172  1167   1005       1.1   
2  1001020300  Alabama  Autauga County      3385  1533   1852       8.0   
3  1001020400  Alabama  Autauga County      4267  2001   2266       9.6   
4  1001020500  Alabama  Autauga County      9965  5054   4911       0.9   

   White  Black  Native  ...  Walk  OtherTransp  WorkAtHome  MeanCommute  \
0   86.3    5.2     0.0  ...   0.5          0.0         2.1         24.5   
1   41.6   54.5     0.0  ...   0.0          0.5         0.0         22.2   
2   61.4   26.5     0.6  ...   1.0          0.8         1.5         23.1   
3   80.3    7.1     0.5  ...   1.5          2.9         2.1         25.9   
4   77.5   16.4     0.0  ...   0.8          0.3         0.7         21.0   

   Employed  PrivateWork  PublicWork  SelfEmployed  FamilyWork  Unemployment  
0       881         74.2        21.2           4.5         0.0           4.6  
1       852         75.9        15.0           9.0         0.0           3.4  
2      1482         73.3        21.1           4.8         0.7           4.7  
3      1849         75.8        19.7           4.5         0.0           6.1  
4      4787         71.4        24.1           4.5         0.0           2.3  

[5 rows x 37 columns]

In [6]:
df_target = df[['Income']]

In [7]:
df = df.drop(['Income'], axis = 1)

In [8]:
np.unique(df_target['Income'], return_counts = True)

(array([     0,   2692,   2702, ..., 248438, 249219, 249750]),
 array([1116,    1,    1, ...,    1,    1,    1]))

In [9]:
df.columns

Index(['TractId', 'State', 'County', 'TotalPop', 'Men', 'Women', 'Hispanic',
       'White', 'Black', 'Native', 'Asian', 'Pacific', 'VotingAgeCitizen',
       'IncomeErr', 'IncomePerCap', 'IncomePerCapErr', 'Poverty',
       'ChildPoverty', 'Professional', 'Service', 'Office', 'Construction',
       'Production', 'Drive', 'Carpool', 'Transit', 'Walk', 'OtherTransp',
       'WorkAtHome', 'MeanCommute', 'Employed', 'PrivateWork', 'PublicWork',
       'SelfEmployed', 'FamilyWork', 'Unemployment'],
      dtype='object')

In [10]:
df = df.drop(['TractId','County', 'Unemployment'],axis = 1)

In [11]:
np.unique(df['State'], return_counts = True)

(array(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California',
        'Colorado', 'Connecticut', 'Delaware', 'District of Columbia',
        'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana',
        'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland',
        'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi',
        'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
        'New Jersey', 'New Mexico', 'New York', 'North Carolina',
        'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania',
        'Puerto Rico', 'Rhode Island', 'South Carolina', 'South Dakota',
        'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington',
        'West Virginia', 'Wisconsin', 'Wyoming'], dtype=object),
 array([1181,  167, 1526,  686, 8057, 1249,  833,  218,  179, 4245, 1969,
         351,  298, 3123, 1511,  825,  770, 1115, 1148,  358, 1406, 1478,
        2813, 1338,  664, 1393,  271,  532,  687,  295, 2010,  499, 4918,
        2195,

In [12]:
np.unique(df['Men'], return_counts = True)

(array([    0,     1,     2, ..., 22181, 28658, 32266]),
 array([715,   1,   2, ...,   1,   1,   1]))

In [28]:
def tipo_Men(line):
    if line == '0' :
        return '0'
    elif line >= '0.1':
            return '1'

In [29]:
df['Men_']   = df['Men'].apply(lambda x: tipo_Men(x))
df_Men = pd.get_dummies(df['Men_'], dummy_na=True)

In [30]:
df_Men.columns

Index(['1', nan], dtype='object')

In [31]:
df_Men.columns   = [  '1','No_def_men' ]


In [32]:
np.unique(df_Men,return_counts = True)

(array([0, 1], dtype=uint8), array([74001, 74001]))

In [ ]:
np.unique(df['Women'], return_counts = True)

In [ ]:
def tipo_Men(line):
    if line == '0' :
        return '0'
    else :
        return '1

In [ ]:
np.unique(df['Hispanic'], return_counts = True)

In [ ]:
def tipo_Men(line):
    if line == '0' :
        return '0'
    else :
        return '1

In [ ]:
np.unique(df['White'], return_counts = True)

In [ ]:
def tipo_Men(line):
    if line == '0' :
        return '0'
    else :
        return '1

In [ ]:
np.unique(df['Native'], return_counts = True)

In [ ]:
def tipo_Men(line):
    if line == '0' :
        return '0'
    else :
        return '1

In [ ]:
np.unique(df['Asian'], return_counts = True)

In [ ]:
def tipo_Men(line):
    if line == '0' :
        return '0'
    else :
        return '1

In [ ]:
np.unique(df['Pacific'], return_counts = True)

In [ ]:
def tipo_Men(line):
    if line == '0' :
        return '0'
    else :
        return '1

In [ ]:
np.unique(df['VotingAgeCitizen'], return_counts = True)

In [ ]:
def tipo_Men(line):
    if line == '0' :
        return '0'
    else :
        return '1

In [ ]:
np.unique(df['IncomeErr'], return_counts = True)

In [ ]:
def tipo_Men(line):
    if line == '0' :
        return '0'
    else :
        return '1

In [ ]:
np.unique(df['IncomePerCap'], return_counts = True)

In [ ]:
def tipo_Men(line):
    if line == '0' :
        return '0'
    else :
        return '1

In [ ]:
np.unique(df['IncomePerCapErr'], return_counts = True)

In [ ]:
def tipo_Men(line):
    if line == '0' :
        return '0'
    else :
        return '1

In [ ]:
np.unique(df['Poverty'], return_counts = True)

In [ ]:
def tipo_Men(line):
    if line == '0' :
        return '0'
    else :
        return '1

In [ ]:
np.unique(df['ChildPoverty'], return_counts = True)

In [ ]:
def tipo_Men(line):
    if line == '0' :
        return '0'
    else :
        return '1

In [ ]:
np.unique(df['Professional'], return_counts = True)

In [ ]:
def tipo_Men(line):
    if line == '0' :
        return '0'
    else :
        return '1

In [ ]:
np.unique(df['Service'], return_counts = True)

In [ ]:
def tipo_Men(line):
    if line == '0' :
        return '0'
    else :
        return '1

In [ ]:
np.unique(df['Office'], return_counts = True)

In [ ]:
def tipo_Men(line):
    if line == '0' :
        return '0'
    else :
        return '1

In [ ]:
np.unique(df['Construction'], return_counts = True)

In [ ]:
def tipo_Men(line):
    if line == '0' :
        return '0'
    else :
        return '1

In [ ]:
np.unique(df['Production'], return_counts = True)

In [ ]:
def tipo_Men(line):
    if line == '0' :
        return '0'
    else :
        return '1

In [ ]:
np.unique(df['Drive'], return_counts = True)

In [ ]:
def tipo_Men(line):
    if line == '0' :
        return '0'
    else :
        return '1

In [ ]:
np.unique(df['Carpool'], return_counts = True)

In [ ]:
def tipo_Men(line):
    if line == '0' :
        return '0'
    else :
        return '1

In [ ]:
np.unique(df['Transit'], return_counts = True)

In [ ]:
def tipo_Men(line):
    if line == '0' :
        return '0'
    else :
        return '1

In [ ]:
np.unique(df['Walk'], return_counts = True)

In [ ]:
np.unique(df['OtherTransp'], return_counts = True)

In [ ]:
np.unique(df['WorkAtHome'], return_counts = True)

In [ ]:
np.unique(df['MeanCommute'], return_counts = True)

In [ ]:
np.unique(df['Employed'], return_counts = True)

In [ ]:
np.unique(df['PrivateWork'], return_counts = True)

In [ ]:
np.unique(df['PublicWork'], return_counts = True)

In [ ]:
np.unique(df['SelfEmployed'], return_counts = True)

In [ ]:
np.unique(df['FamilyWork'], return_counts = True)

In [ ]:
np.unique(df['State'], return_counts = True)

In [ ]:
df_state = pd.get_dummies(df['State'], dummy_na=True)

In [ ]:
df_state.columns

In [ ]:
df_state.columns   =[             'Alabama',               'Alaska',              'Arizona',
                   'Arkansas',           'California',             'Colorado',
                'Connecticut',             'Delaware', 'District_of_Columbia',
                    'Florida',              'Georgia',               'Hawaii',
                      'Idaho',             'Illinois',              'Indiana',
                       'Iowa',               'Kansas',             'Kentucky',
                  'Louisiana',                'Maine',             'Maryland',
              'Massachusetts',             'Michigan',            'Minnesota',
                'Mississippi',             'Missouri',              'Montana',
                   'Nebraska',               'Nevada',        'New_Hampshire',
                 'New_Jersey',           'New_Mexico',             'New_York',
             'North_Carolina',         'North_Dakota',                 'Ohio',
                   'Oklahoma',               'Oregon',         'Pennsylvania',
                'Puerto_Rico',         'Rhode_Island',       'South_Carolina',
               'South_Dakota',            'Tennessee',                'Texas',
                       'Utah',              'Vermont',             'Virginia',
                 'Washington',        'West_Virginia',            'Wisconsin',
                    'Wyoming',                    'No_Def_State']

In [ ]:
df_state = df_state.drop(['No_Def_State'], axis = 1)

In [ ]:
df_menu = df

In [ ]:
df_menu = pd.concat([df_menu, df_state ], axis=1, join="inner")

In [ ]:
df_menu.head(4)

In [ ]:
df_menu.isnull().sum()

In [ ]:
df_target.isnull().sum()

In [ ]:
df_menu.columns

In [ ]:
df_menu = df_menu.drop(['State'], axis = 1)

In [ ]:
df_target.columns

In [ ]:
np.unique(df_target['Income'],return_counts = True)

In [ ]:
min_max_scaler = preprocessing.MinMaxScaler()

In [ ]:
x = df_menu

In [ ]:
x = min_max_scaler.fit_transform(x)

In [ ]:
y = df_target

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20)

In [ ]:
from sklearn import linear_model

In [ ]:
reg = linear_model.LinearRegression()

In [ ]:
np.unique(x_train, return_counts = True)

In [ ]:
np.unique(x_test, return_counts = True)

In [ ]:
np.unique(y_train, return_counts = True)

In [ ]:
np.unique(y_test, return_counts = True)

In [ ]:
reg.fit(x_train,y_train)

In [ ]:
y_pred = reg.predict(x_test)

In [ ]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error

In [ ]:
print("MAE",mean_absolute_error(y_test,y_pred))

In [ ]:
print("RMSE",np.sqrt(mean_squared_error(y_test,y_pred)))

In [ ]:
print("RMSE",np.log(np.sqrt(mean_squared_error(y_test,y_pred))))

In [ ]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test,y_pred)
print(r2)

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
len(x_test), len(y_test), len(y_pred)

In [ ]:
x_test

In [ ]:
dfx = pd.DataFrame(x_test)

In [ ]:
dfx.head()

In [ ]:
dfx = dfx.reset_index()

In [ ]:
dfx.head()

In [ ]:
dfx['y_test'] = y_test

In [ ]:
dfx['y_pred'] = y_pred

In [ ]:
dfx = dfx.query(''' y_test > 0 ''')

In [ ]:
df_sample = dfx[['index','y_test','y_pred']].sample(20)
df_sample = df_sample.sort_values(by=['index'], ascending=True)

In [ ]:
df_sample

In [ ]:
plt.figure()
plt.scatter(df_sample['index'],df_sample['y_test'],color="blue")
plt.plot(df_sample['index'],df_sample['y_test'],color="blue")
plt.scatter(df_sample['index'],df_sample['y_pred'],color="red")
plt.plot(df_sample['index'],df_sample['y_pred'],color="red")


In [ ]:
dfx = dfx.sort_values(by=['index'], ascending=True)

In [ ]:
dfx = dfx.head(100)

In [ ]:
plt.figure()
plt.scatter(dfx['index'],dfx['y_test'],color="blue")
plt.plot(dfx['index'],dfx['y_test'],color="blue")
plt.scatter(dfx['index'],dfx['y_pred'],color="red")
plt.plot(dfx['index'],dfx['y_pred'],color="red")

In [ ]:
np.unique(x_train, return_counts = True)

In [ ]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline
from sklearn.linear_model import LinearRegression

In [ ]:
degree=3
polyreg=make_pipeline(PolynomialFeatures(degree),LinearRegression())
polyreg.fit(x_train,y_train)

In [ ]:
y_pred = polyreg.predict(x_test)

In [ ]:
print("MAE",mean_absolute_error(y_test,y_pred))
print("RMSE",np.sqrt(mean_squared_error(y_test,y_pred)))
print("RMSE",np.log(np.sqrt(mean_squared_error(y_test,y_pred))))

In [ ]:
import matplotlib.pyplot as pltplt.figure()

In [ ]:
plt.scatter(x_test,y_test)
plt.plot(x_test,y_pred,color="black")
plt.title("Polynomial regression with degree "+str(degree))plt.show()

https://www.analyticsvidhya.com/blog/2021/05/know-the-best-evaluation-metrics-for-your-regression-model/

https://towardsdatascience.com/polynomial-regression-with-scikit-learn-what-you-should-know-bed9d3296f2